---
title: "Dual Target Cost - Experiment 1"
author: "James D. Dunn"
date: "15 June 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(PairedData)
library(ez)
library(effsize)
library(knitr)
library(kableExtra)

experiment1Data <- read_csv("Experiment1Data.csv")
windowsFonts(Arial=windowsFont("Arial"))
```

```{r dataprep}
experiment1Data$Pptno <- factor(experiment1Data$Pptno)
experiment1Data$NoTargets <- factor(experiment1Data$NoTargets)

# get means for each participant for each condition


summaryDataExp1 <- experiment1Data %>%
  group_by(Pptno,TrialType) %>%
  summarise(mean_Errors = mean(TotalErrors),mean_TrialLength = mean(TrialLength))

conditionMeansExp1 <- summaryDataExp1 %>%
  group_by(TrialType) %>%
  summarise(group_Errors = mean(mean_Errors),group_TrialLength = mean(mean_TrialLength))

conditionSDExp1 <- summaryDataExp1 %>%
  group_by(TrialType) %>%
  summarise(group_ErrorsSD = sd(mean_Errors),sd_TrialLength = sd(mean_TrialLength))

conditionMeansExp1$TrialType <- factor(conditionMeansExp1$TrialType)
levels(conditionMeansExp1$TrialType) <- c("1IMG","1ID","2ID")

conditionSDExp1$TrialType <- factor(conditionSDExp1$TrialType)
levels(conditionSDExp1$TrialType) <- c("1IMG","1ID","2ID")

#dataframes for significant interactions
t1<- summaryDataExp1 %>%
  filter(TrialType != "3")
t2<- summaryDataExp1 %>%
  filter(TrialType != "2")
t3<- summaryDataExp1 %>%
  filter(TrialType != "1")

t1$TrialType <- factor(t1$TrialType)
t2$TrialType <- factor(t2$TrialType)
t3$TrialType <- factor(t3$TrialType)

levels(t1$TrialType) <- c("1IMG","1ID")
levels(t2$TrialType) <- c("1IMG","2ID")
levels(t3$TrialType) <- c("1ID","2ID")
summaryDataExp1$TrialType <- factor(summaryDataExp1$TrialType)
levels(summaryDataExp1$TrialType) <- c("1IMG","1ID","2ID")

kable(conditionMeansExp1)
kable(conditionSDExp1)
```



```{r Demographics}
demographics <- experiment1Data %>%
  group_by(Pptno) %>%
  summarise(gender = mean(Gender),age = mean(Age))
demographics$gender <- factor(demographics$gender)
levels(demographics$gender) <- c("Female","Male")
summary(demographics)

ageSummary <- demographics %>%
  summarise(meanAge = mean(age), stdAge = sd(age))

glimpse(ageSummary)
```



```{r Visualise}
ggplot(summaryDataExp1, aes(x = TrialType, y = mean_Errors)) +
  geom_violin(aes(fill=TrialType),scale='count',color = "black", size = 1,show.legend = F) +
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Arial'),
        legend.title=element_blank(),
        plot.title = element_text(face="bold", size = 30, hjust = 0.5),
        axis.title = element_text(face="bold", size = 12),
        axis.text = element_text(colour="black", size = 11),
        panel.background = element_rect(fill = 'white'),
        strip.text= element_text(face='bold', size =24),
        strip.background = element_rect(fill = 'white'),
        legend.position="bottom") +
  labs(x="Template",y="Mean trial errors")+
  ylim(0,15) +
  geom_boxplot(width=.12,fill=I('black'), notch=T, col='grey40',outlier.fill='black',outlier.colour ='black',outlier.color  ='black',outlier.size = 3) +
  stat_summary(fun='mean', geom='point', shape=20,size =5, col='white')

ggsave("Figure2.png")
ggsave("Figure2.tiff",dpi = 300)

ggplot(summaryDataExp1, aes(x = TrialType, y = mean_TrialLength)) +
  geom_violin(aes(fill=TrialType),scale='count',color = "black", size = 1,show.legend = F) +
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Arial'),
        legend.title=element_blank(),
        plot.title = element_text(face="bold", size = 30, hjust = 0.5),
        axis.title = element_text(face="bold", size = 12),
        axis.text = element_text(colour="black", size = 11),
        panel.background = element_rect(fill = 'white'),
        strip.text= element_text(face='bold', size =24),
        strip.background = element_rect(fill = 'white'),
        legend.position="bottom") +
  labs(x="Template",y="Mean trial length (s)")+
  # ylim(0,15) +
  geom_boxplot(width=.12,fill=I('black'), notch=T, col='grey40',outlier.fill='black',outlier.colour ='black',outlier.color  ='black',outlier.size = 3) +
  stat_summary(fun='mean', geom='point', shape=20,size =5, col='white')

ggsave("SupFig1.png")
ggsave("SupFig1.tiff",dpi = 300)
```


```{r Errors analysis}
summaryDataExp1.ez <- ezANOVA(data = summaryDataExp1, dv = .(mean_Errors), wid = .(Pptno), within = .(TrialType), detailed = TRUE, type = 3)
summaryDataExp1.ez

#T TEST
#1IMG - 1ID
t.test(mean_Errors ~ TrialType,data = t1, paired=TRUE)
cohen.d(mean_Errors ~ TrialType,data = t1, paired=TRUE)
#1IMG - 2ID
t.test(mean_Errors ~ TrialType,data = t2, paired=TRUE)
cohen.d(mean_Errors ~ TrialType,data = t2, paired=TRUE)

#1ID - 2ID
t.test(mean_Errors ~ TrialType,data = t3, paired=TRUE)
cohen.d(mean_Errors ~ TrialType,data = t3, paired=TRUE)

```

```{r Trial Length analysis}
summaryDataExp1RT.ez <- ezANOVA(data = summaryDataExp1, dv = .(mean_TrialLength), wid = .(Pptno), within = .(TrialType), detailed = TRUE, type = 3)
summaryDataExp1RT.ez

#T TEST
#1IMG - 1ID
t.test(mean_TrialLength ~ TrialType,data = t1, paired=TRUE)
cohen.d(mean_TrialLength ~ TrialType,data = t1, paired=TRUE)
#1IMG - 2ID
t.test(mean_TrialLength ~ TrialType,data = t2, paired=TRUE)
cohen.d(mean_TrialLength ~ TrialType,data = t2, paired=TRUE)

#1ID - 2ID
t.test(mean_TrialLength ~ TrialType,data = t3, paired=TRUE)
cohen.d(mean_TrialLength ~ TrialType,data = t3, paired=TRUE)
```